# Python and Numpy Introduction

This notebook shall give you a small overview about the basics for [Python](https://www.python.org/) and the [Numpy](https://numpy.org/) library.

Python is a popular programming language that is used for several, plattform independent development tasks.

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you will see that they have some similarities. An overview of MATLAB vs. Numpy can be found [here](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)

**Python**
* [1. Python](http://sixthresearcher.com/wp-content/uploads/2016/12/Python3_reference_cheat_sheet.pdf)
* [2. Python](https://perso.limsi.fr/pointal/_media/python:cours:mementopython3-english.pdf)

**Numpy**
* [1. Numpy_CheatSheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
* [2. Numpy_CheatSheet](http://datasciencefree.com/numpy.pdf)
* [3. Numpy_CheatSheet](https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf)
* [4. Numpy_CheatSheet (array)](https://blog.finxter.com/wp-content/uploads/2019/04/11-Numpy-Cheat-Sheet.pdf)

We will just give an overview for some Python and Numpy functionality that can be useful during this workshop. We will also introduce the [matplotlib](https://matplotlib.org/) for plotting data

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

# Python

Python has a simple syntax similar to the English language that allows developers to write programs with fewer lines than some other programming languages. Further, Python can be treated in a procedural way, an object-oriented way or a functional way.

## Basic types
Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.

### Numbers
Integers and floats work as you would expect from other languages:

In [ ]:
# This is a comment
print("Hello") # Prints "Hello"
print("="*5)   # Prints "====="
x = 42         # Define an interger variable
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "42"
print(x + 1)   # Addition; prints "43"
print(x - 1)   # Subtraction; prints "41"
print(x * 2)   # Multiplication; prints "84"
print(x ** 2)  # Exponentiation; prints "1764"
x += 1         # Inplace Addition;
print(x)       # Prints "43"
x *= 2         # Inplace Multiplication;
print(x)       # Prints "86"
y = 2.5        # Define a float variable
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"
n = None       # Define a none variable (The None keyword is used to define a null value, or no value at all)
               # None is not the same as 0, False, or an empty string. 
               # None is a datatype of its own (NoneType) and only None can be None.
print(type(n)) # Prints "<class 'NoneType'>"

### Booleans
Python implements all of the usual operators for Boolean logic, but uses English words rather than known C/C++ symbols (&&, ||, etc.):

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

### Strings
Python supports strings with a lot of useful functions. We will show some here using the great "hello world".

[String Methods](https://docs.python.org/3.5/library/stdtypes.html#string-methods)

In [ ]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"
val = 12.345678
print(f"{hello} {world} {val:.2f}")     # f-String style formatting 


# Some usefull Methods
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"
print(s[2])            # Prints "l", the 3. character of s (zero index)

## Containers
Containers are the most important part when working with python or neural networks. We will show some types of containers that are used by other submodules also.
* [Lists](https://docs.python.org/3.5/tutorial/datastructures.html#more-on-lists): is a collection which is ordered and changeable. Allows duplicate members.
* [Tuples](https://docs.python.org/3.5/tutorial/datastructures.html#tuples-and-sequences): is a collection which is ordered and unchangeable. Allows duplicate members.
* [Sets](https://docs.python.org/3.5/library/stdtypes.html#set):  is a collection which is unordered and unindexed. **No** duplicate members.
* [Dictionaries](https://docs.python.org/3.5/library/stdtypes.html#dict): is a collection which is unordered, changeable and indexed. **No** duplicate members.


Further we will introduce the `loop` functionality to access elements within containers and we will show how `slicing` works. Slicing in python means taking elements from one given index to another given index. We will see slicing again in the context of numpy arrays.

### Lists
List is the same as an array but it is rezizable and can contain different types

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

#### Loops

In [ ]:
nums = list(range(5,10,2)) 

# Simple Loop
for n in nums:
    print(n)
    
# Indexing using Enumerate
for i,n in enumerate(nums):  # Use built-in method "enumerate" to access the index
    print(f"#{i}: {n}")

#### Comprehension
Transforming ont type of data to another

In [ ]:
import random
nums = random.sample(range(0, 10), 5)

print(nums)

squares = []
# With for loop
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

# List comprehension
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

# List comprehension with if condition
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

# List comprehension with if-else condition
even_squares = [x ** 2 if x % 2 == 0 else x/2 for x in nums]
print(even_squares)  # Prints "[0, 0.5, 4, 1.5, 16]"

# Sorting nums lists
sorted(nums) 

#### Slicing


In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)    

### Dictionaries
A dictionary stores (key, value) pairs, similar to a Map in Java. You can use it like this:

In [ ]:
d = {             # Create a new dictionary with some data
  "name": "Elektrobit",
  "site": "Radolfzell",
  "employees": 20
}  
print(d['name'])       # Get an entry from a dictionary; prints "Elektrobit"
print('site' in d)     # Check if a dictionary has a given key; prints "True"
d['manager'] = 'Zosel' # Set an entry in a dictionary
print(d['manager'])      # Prints "Zosel"
# print(d['kicker'])  # KeyError: 'kicker' not a key of d :-)
print(d.get('kicker', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('employees', 'N/A'))    # Get an element with a default; prints "wet"
del d['site']         # Remove an element from a dictionary
print(d.get('site', 'N/A')) # "site" is no longer a key; prints "N/A"

#### Loops: 
It is easy to iterate over the keys in a dictionary.
If you want access to keys and their corresponding values, use the `items` method:

In [ ]:
d = {'human': 2, 'dog': 4, 'spider': 8}


for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
    
print()
print("With 'item' method")
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

print()
print("Sorted Dictionary")
print(d)                   # Prints dictionary "{'human': 2, 'dog': 4, 'spider': 8}"
print(sorted(d))           # Prints list of sorted keys "['dog', 'human', 'spider']"
print(sorted(d.items()))   # Prints list of sorted tuples "[('dog', 4), ('human', 2), ('spider', 8)]"

#### Comprehension
Similar to list comprehension, but allow to esily construct dictionaries

In [ ]:
nums = range(5)   # range creates an iterable
print(nums)       # Prints "range(5)"
print(type(nums)) # Prints "<class 'range'>" 
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

### Sets
A set is an unordered collection of distinct elements.

In [ ]:
animals = {'cat', 'dog'}
print(animals)            # Prints "{'cat', 'dog'}"
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"
animals.update(["horse", "monkey", "alpaka"]) # Add multiple items to a set use "update"
print(animals)            # Prints the updated animals
print(sorted(animals))    # Prints sorted animals as list "['alpaka', 'dog', 'fish', 'horse', 'monkey']"

#### Loops
Iterating over a `set` has the same syntax as iterating over a `list`; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal)) # Prints "#1: fish", "#2: dog", "#3: cat"

print()
print("Sorted Set")
for idx, animal in enumerate(sorted(animals)):
    print('#%d: %s' % (idx + 1, animal)) # Prints "#1: cat", "#2: dog", "#3: fish"

#### Comprehension
Like `lists` and `dictionaries`, we can easily construct `sets` using set comprehensions:

In [ ]:
from math import sqrt
nums = list(range(10))  # Creates a list from 0..10
print(nums)            
nums_list = [int(sqrt(x)) for x in nums]  # Take the sqrt of every item in x as integer as a "list"
print(nums_list)  # Print [0, 1, 1, 1, 2, 2, 2, 2, 2, 3] 

nums_set = {int(sqrt(x)) for x in nums}  # Take the sqrt of every item in x as integer as a "set"
print(nums_set)  # Prints "{0, 1, 2, 3}"

# We can also create a set directly from a list
print(set(nums_list)) # Prints "{0, 1, 2, 3}"

### Tuples
A tuple is an (immutable/unchangeable) ordered list of values. A tuple is in many ways similar to a list. 
One of the most important differences is that 
* tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. 

This is because keys in dictionaries is an unchangeable value also

In [ ]:
d = {(x, x + 1): x for x in range(5)}  # Create a dictionary with tuple keys
print(d)
t = (3, 4)        # Create a tuple
print(t)          # Prints (3,4)
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "3"
print(d[(1, 2)])  # Prints "1"

print("")
print("Tuple manipulation")
#t[0] = 4         # Unomment this line leads to an error because item assignment is not allowed
tl = list(t)      # Create a list from the tuple
tl[0]=2; tl[1]=3  # Modify the list
t = tuple(tl)     # Create a tuple
print(t)          # Prints (2,3) 
print(d[t])       # Prints "2"


# Numpy
As mentioned in the introduction, `numpy` (numerical python) is the core library for scientific programming. In the following cells we will give you an introduction to numpy and show you how you can use in practice.

## Why use Numpy
In Python we have lists that serve the purpose of arrays, but they are slow to process.
Numpy aims to provide an array object that is up to 50x faster that traditional Python lists. The array object in Numpy is called [`ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), it provides a lot of supporting functions that make working with `ndarray` easy. Arrays are very frequently used in data science, where speed and resources are very important.

## Why is Numpy faster than Python lists
Unlike lists NumPy arrays are stored at one continuous place in memory so processes can access and manipulate them very efficiently. As you know from programming or at least the process of memory caching it is always good to load memory as fast as possible. 

In Computer science this is called `locality of reference`. This is the main reason why Numpy is faster than Python lists

Further, Numpy arrays are optimized to work with common CPU, GPU an TPU (Tensor Programming Unit)

## Numpy Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
* The number of dimensions is the rank of the array; 
* The shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

### 0-D Arrays (Scalars)
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
a = np.array(42)
print(type(a))  # Prints "<class 'numpy.ndarray'>"
print(a.shape)  # Prints "()"
a               

### 1-D Arrays (Vectors)
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array or vector.

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints the shape "(3,)"
print(a[0], a[1], a[2])   # Prints the elements at indices "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
print(a.ndim)             # Prints the dimension "1"

### 2-D Arrays (Matrix)
An array that has 1-D arrays as its elements is called a 2-D array or matrix.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])   # Create a rank 2 array
print(type(a))                         # Prints "<class 'numpy.ndarray'>"
print(a.shape)                         # Prints the shape "(2,3)"
print(a[0, 0], a[0, 1], a[1, 0])       # Prints the elements at indices "1 2 4"
print(a.ndim)                          # Prints the dimension "2"

### N-D Arrays (Tensor)
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.

In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]],       # Create a rank 3 array
              [[7, 8, 9], [10, 11, 12]]])
print(type(a))                              # Prints "<class 'numpy.ndarray'>"
print(a.shape)                              # Prints the shape "(2,3,3)"
print(a[0, 0], a[0, 1], a[1, 0], a[1, 1])   # Prints elements at indices "[1 2 3] [4 5 6] [7 8 9] [10 11 12]"
print(a.ndim)                               # Prints the dimension "2"
print(a[0, 1, 2])                           # Prints "6"

#### Example Explained
`a = np.array([[[1, 2, 3], [4, 5, 6]],       
              [[7, 8, 9], [10, 11, 12]]])`

<br><br>
The N-D array `a` has `N=3` dimentions `a[first_dim,second_dim,third_dim]`

Now we go step by step to explain why `a[0, 1, 2]` prints the value `6`.

**Fist Dimension**
The first number represents the first dimension, which contains two arrays:<br>
`[[1, 2, 3], [4, 5, 6]]` <br>
and:<br>
`[[7, 8, 9], [10, 11, 12]]`<br>
Since we selected 0, we are left with the first array:<br>
`[[1, 2, 3], [4, 5, 6]]`<br>

<br>

**Second Dimension**
The second number represents the second dimension, which also contains two arrays (the two from **First Dimenion**):<br>
`[1, 2, 3]` <br>
and: <br>
`[4, 5, 6]` <br>
Since we selected 1, we are left with the second array: <br>
`[4, 5, 6]` <br>

**Third Dimension**
The third number represents the third dimension, which contains three values (the valued from the **Second Dimention**):<br>
` Index 0: 4 
Index 1: 5 
Index 2: 6`

Since we selected `index 2`, we end up with the third value:
`6`

## Numpy functions
Numpy also provides many functions to create arrays. We provide some functions you shoud know.
In the [Numpy_CheatSheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) you will find some more useful functions

In [ ]:
a = np.zeros((2,2))          # Create an array of all zeros
print("np.zeros:\n", a) 

a = np.ones((1,2))           # Create an array of all ones
print("np.ones:\n", a)

a = np.full((2,2), 7)        # Create a constant array
print("np.full:\n", a)  

a = np.eye(2)                # Create a 2x2 identity matrix
print("np.eye:\n", a)  

a = np.random.random((2,2))  # Create an array filled with random values
print("np.random.random:\n", a)  

a = np.random.choice([0,1],size=10,p=[0.8,0.2]) # Toss a biased Coin
print("np.random.choice:\n", a)  

a = np.linspace(0,10,11)     #  Create an array with 11 elements, last element included (endpoint=True)
print("np.linspace:\n", a) 

a = np.arange(0,1,0.2)       #  Create an array with evenly spaced values within a given interval
print("np.arange:\n", a) 

a = np.repeat(3,3)           #  Creates an array with repeated number
print("np.repeat:\n", a) 
a = np.repeat([0,1,2],3)     #  Creates an array with elementwise array reptitions
print("np.repeat:\n", a) 

a = np.tile([0,1,2],3)          # Creates an array by repeating A the number of times given by reps
print("np.tile:\n", a) 
a = np.tile([0,1,2],[3,1])      # Stack 3 copies of a on top of each other
print("np.tile:\n", a) 

a = np.array([[[1, 2, 3], [4, 5, 6]],       # Create a rank 3 array
              [[7, 8, 9], [10, 11, 12]]])
print("a shape:\n", a.shape)
a = np.reshape(a,-1)                        # Reshape to rank 1 array (vector)
print("a (flatten) shape:\n", a.shape)
a = np.reshape(a,(-1,3))                    # Reshape to rank 3 array (matrix)
print("a shape:\n", a.shape)

## Array Indexing/Sclicing
Numpy offers several ways to index into arrays. We will show the common indexing and slicing techniques. More information about indexing and slicing can be found in the [documentation](https://numpy.org/doc/stable/reference/arrays.indexing.html)

`Slicing:` Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

<br>
Slicing in python means taking elements from one given index to another given index.

* We pass slice instead of index like this: `[start:end]`

* We can also define the step, like this: `[start:end:step]`

* If we don't pass start its considered 0

* If we don't pass end its considered length of array in that dimension

* If we don't pass step its considered 1

### Indexing and Slicing

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4],    # (0,4)
              [5,6,7,8],    # (1,4) 
              [9,10,11,12]])# (2,4)
print("a:\n",a)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
# In other words: From the first and second element, slice elements from index 1 to index 3 (not included)
b = a[:2, 1:3]
print("b:\n",b)


# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print("a[0, 1]:\n", a[0, 1])   # Prints "2"
b[0, 0] = 42     # b[0, 0] is the same piece of data as a[0, 1]
print("a[0, 1]:\n", a[0, 1])   # Prints "42"

### Mixture of integer indexing and slicing
You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. 

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("a:\n",a)

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print("Rank 1 view of the second row of a: \n",row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print("Rank 2 view of the second row of a: \n", row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print("Rank 1 view of the second column of a: \n",col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print("Rank 2 view of the second column of a: \n",col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

### Integer array indexing
When you index into numpy arrays using slicing, the resulting array view **will always be a subarray of the original array**.

In contrast, **integer array indexing** allows you to construct arbitrary arrays using the data from another array. 

In [ ]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])
print("a\n",a)
print("a.shape\n",a.shape)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], #[[1 2]
                   #[3 4]
                   #[5 6]]
        
        [0, 1, 0]] # Use index 0 from [1 2], index 1 from [3 4] and index 0 from [5 6]
     )  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0],  # Index 0 from first array [1,2] (Note this is the array)
                a[1, 1],  # Index 1 from second array [3,4] (Note this is the array)
                a[2, 0]]) # Index 0 from third array [3,4]
     )  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print("Integer array indexing (same array):\n",a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print("Integer array indexing (new array):\n", np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

#### Useful tricks
One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print("a:\n",a)

# Create an array of indices
b = np.array([0, 2, 0, 1])
print("b:\n",b)

# Select one element from each row of a using the indices in b
print("Select one element from each row of a using the indices in b:\n",a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print("a (mutated):\n",a)

## Boolean Array indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition

In [ ]:
a = np.array([[1,2], 
              [3,4], 
              [5,6]])
print("a:\n",a)
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print("bool_idx:\n",bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"


# ogid returns open and meshgrid dense multi-dimentional arrays
x,y= np.ogrid[0:random.randint(2,10):1,
              0:random.randint(4,8):1]
print("x\n",x.flatten())
print("y\n",y.flatten())
# Using numpy.where function for array manipulation 
a = np.where(x==y,x,-1) # Returns x if x==y, else -1
print("a (mutated):\n",a)

# Matplotlib
[Matplotlib](https://matplotlib.org/) is a plotting library. In this section give a brief introduction to the matplotlib.pyplot module, which provides a plotting system similar to that of MATLAB.

## Plotting
The most important function in matplotlib is [plot](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.plot), which allows you to plot 2D data.

In [ ]:
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()  # You should call plt.show() to make graphics appear.

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

## Subplots
You can plot different things in the same figure using the [`subplot`](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot) function.

`subplot(row,column,index)`

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has 2 rows and 1 column,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

## Images
You can use the [`imshow`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html?highlight=imshow#matplotlib.pyplot.imshow) function to show images.

In [ ]:
img = cv2.imread('Pictures/Lenna.png')
img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)  # Convert to right color space
print(img.shape)                            # Shape of the image
img_rand = img * np.random.uniform(high=10.0,size=3) # Manipulate image channgel with random vlaues

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the manipulated image
plt.subplot(1, 2, 2)

# A slight problem with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(img_rand))
plt.show()